### ISSUE TITLE
Output two pids at once for MMT/TLV stream

### ISSUE THREAD

**Issue by MMT-TLVassociation** [wangf1978/DumpTS#8]
The current version DumpTS needs to run twice, if the output for two pids (for audio&video) needed.
For example, dumpts sample.mmts --srcfmt=mmt --output=test.hevc --pid=0xa001 --CID=2
In this case, pid=0xa001 is video data only.

For audio data(0xa041), dumpts needs to run again,
dumpts sample.mmts --srcfmt=mmt --output=test.aac --pid=0xa041 --CID=2

I think it's good to process two pids at once like this,
 dumpts sample.mmts --srcfmt=mmt --output=test.hevc&test.aac --pid=0xa001&0xa041 --CID=2

What do you think?

**Comment by wangf1978** [comment]
Good idea! I think it is not hard to implement it based on the current code.
I will consider to support it, if you have already implemented it, that's also good.

**Comment by MMT-TLVassociation** [comment]
Thank you.
Today, I updated DumpMMT.cpp as below,
https://github.com/MMT-TLVassociation/DumpTS/commit/fed5fb8099a0cb05006dd21ddf4244864a0bd6d4#diff-0ea5c26427da85cf198ce147b16bb283

Now we can output two pids at once by the command line,
DumpTS sample.mmts --pid=0xa001&0xa041 --CID=2 output=test.hevc

In this modification, TLV packet is switched by "PIDN" (integer 0 or 1)  which corresponds to each pid.

The output file is, ( PID+output filename)
0xa001test.hevc and 0xa041test.hevc

I'm thinking to test this code for a week.
If you notice it needs any fix, please let me know.

**Comment by wangf1978** [comment]
In order to keep the PID lexer simple, maybe we can support multiple --pid options, for example:
DumpTS sample.mmts --pid=0xa001 --pid=0xa041 --CID=2 output=test.hevc

As for the output filename, I think add PID as the suffix of output filename, it may keep the current style
For exaple, test_a001.hevc and test_a041.hevc

**Comment by MMT-TLVassociation** [comment]
Yes, using "&" in pid, makes code a little complicated.
I'm afraid "g_params["pid"]" can't be used, if supporting multiple --pid options.

**Comment by MMT-TLVassociation** [comment]
The pids output seems working good.
I modified for the output file name as you advised.
When DumpTS sample.mmts --pid="0xa001&0xa041" --CID=2 output=test.hevc
output files are test_0xa001.hevc and test_0xa041.hevc

https://github.com/MMT-TLVassociation/DumpTS/commit/99102747d1d01b1dc24de61c102fbbace11f2fff#diff-0ea5c26427da85cf198ce147b16bb283

I'll make a pull request, if there is no more fix needed.

**Comment by wangf1978** [comment]
Thanks for your contribution, I reviewed it, it is ok for me
